### ISSUE TITLE
Add support for cargo's --profile option

### ISSUE THREAD

**Issue by Kneelawk** [burtonageo/cargo-bundle#106]
# The Issue
Currently, cargo-bundle has no support for a `--profile` option to allow specifying custom build profiles. Cargo added support for this option in Rust 1.57.0. Adding a `--profile` option allows users to specify custom profiles for packaging. For example: one profile with normal release optimizations and one profile with release optimizations and link-time optimizations.

# The Feature Request
The feature request is that cargo-bundle add an option `--profile` that takes a single argument, being the name of the custom profile to use. This will invoke the underlying cargo build command with `--profile` and the custom profile name. The cargo documentation specifies that the build directory used for a custom profile is `target/<profile-name>` where `<profile-name>` is the name of the profile being built.

# The Pull Request
I am working on a PR to solve this issue. It should be linked once complete.

**Comment by vorporeal** [comment]
Hi there - any idea when this change will make it into a published release?  Would love to use it but the current published version (v0.5.0) is over a year old, and I'd prefer not to have our build scripts pull from HEAD.

**Comment by mdsteele** [comment]
I've just published [v0.6.0](https://crates.io/crates/cargo-bundle/0.6.0).
