### ISSUE TITLE
`winit 0.20` fails to compile on aarch64-darwin

### ISSUE THREAD

**Issue by lilyball** [burtonageo/cargo-bundle#114]
I can't run `cargo test` because of the `dev-dependency` on ~~`winit 0.2.0`~~`winit 0.20.0`, which fails to compile on aarch64-darwin. The error in question appears to have been fixed in `winit 0.24.0` (see https://github.com/rust-windowing/winit/pull/1752).

**Comment by maroider** [comment]
Good lord, what an ancient version of winit! Are you sure you didn't mean `0.20.0`?
