### ISSUE TITLE
Project structure issue

### ISSUE THREAD

**Issue by anas-elgarhy** [burtonageo/cargo-bundle#129]
Specifically in the case of the Linux system, you will have a lot of common functions across all package formats that run on Linux, such as generate the desktop file, generating md5sums, generating the icon files, and so on.
So I think it's a good idea to create a `linux` module and separate the common functions into a separate file, like the `common.rs` file.
And from the project structure view, I think it will make the project cleaner.

**Comment by mdsteele** [comment]
Seems reasonable; PRs would be welcome.

**Comment by anas-elgarhy** [comment]
Ok, I'll be happy to make one, please assignee this issue to me

**Comment by mdsteele** [comment]
Thanks!  Assigned.
