### ISSUE TITLE
Create an GitHub action for running the testes on PR's

### ISSUE THREAD

**Issue by anas-elgarhy** [burtonageo/cargo-bundle#131]
I suggest creating a GitHub Action that runs tests on pull requests to improve the code review process and catch potential bugs early. This would help ensure that only high-quality code is merged into the master branch and reduce the likelihood of introducing new issues.

**Comment by anas-elgarhy** [comment]
I'll be happy, If I created it

**Comment by mdsteele** [comment]
Yes, a PR on this would be very welcome

**Comment by anas-elgarhy** [comment]
Ok, please assignee this issue to me.
