### ISSUE TITLE
Dependency specification

### ISSUE THREAD

**Issue by vorner** [burtonageo/cargo-bundle#25]
I know it is still work in progress (mostly because I had to use the code from master instead of the regular released version). I tried to create a .deb package, which went mostly well. However, it would be great if I could somehow specify the dependencies for the package (the deb package currently has none). Or did I miss it somewhere in the documentation?

**Comment by mdsteele** [comment]
Nope, you didn't miss it in the docs -- this is not yet supported (but should be!).
