### ISSUE TITLE
Support to specify different target

### ISSUE THREAD

**Issue by vorner** [burtonageo/cargo-bundle#27]
I can build for a different architecture with `cargo build --target` (for example to build a statically linked binary, or to build a 32bit binary on 64bit system). It would be great if I could pass `--target` to `cargo bundle` as well and it could create a corresponding package. For example, the static binaries would help deploying the same .deb package on both ubuntu and debian systems of different versions in our company instead of having to build a different package for each of them.

**Comment by mdsteele** [comment]
This was added in 782ca5e, although that hasn't been pushed to crates.io yet, so for now you'll need to build cargo-bundle from `master`.  Also, I think there's a bug where `cargo bundle` won't build the binary for you (filed as #28), so you'll need to `cargo build --target=...` before you `cargo bundle --target=...`.

**Comment by vorner** [comment]
Thank you, that is enough for me :-).
