### ISSUE TITLE
cargo-bundle for macOS does not appear to inherit target name from Cargo.toml

### ISSUE THREAD

**Issue by oluseyi** [burtonageo/cargo-bundle#30]
Simple `Cargo.toml` file, looking something like this:
```
[package]
name = "my-project"
version = "0.1.0"
authors = ["Oluseyi Sonaiya <e@mail.domain>"]
```
and simple `Bundle.toml`, like this:
```
identifier = "domain.organization.my-project"
icon = "path/to/icon.png"
copyright = "(C) Organization, 2017"
short_description = "My Project for macOS"
long_description = "My Project lorme ipsum"
```
Consistently, running `cargo bundle` yields an app bundle named `target/debug/.app`. It's a valid app bundle, and I just rename it for convenience, but this is clearly a bug.

Btw, perhaps it explains https://github.com/burtonageo/cargo-bundle/issues/28.

**Comment by mdsteele** [comment]
Yep, this is basically the same bug as issue #26, but for OSX bundles.  I believe it was fixed in master by PR #29, but that hasn't been pushed out to crates.io quite yet.
