### ISSUE TITLE
Consider refactoring of config loading

### ISSUE THREAD

**Issue by application-developer-DA** [burtonageo/cargo-bundle#34]
It would be nice to use `serde` and `serde-derive` crates in order to write the TOML config parsing in an elegant way (without the boilerplate code and self-written macro rules).

Having `serde-derive` would allow usage of `#[derive(Deserialize)]` on the corresponding config structures, so the parsing would as simple as `let config: Settings = toml::from_str(buffer)?;`

**Comment by mdsteele** [comment]
Thanks for the suggestion!  This has been fixed.
