### ISSUE TITLE
allow passing `--features=xxx` argument

### ISSUE THREAD

**Issue by paulrouget** [burtonageo/cargo-bundle#37]
`cargo bundle` will call `cargo build` if necessary. Because of that, `cargo bundle` should support the `--features=xxx` argument, the same way `cargo run` does.

**Comment by ArturKovacs** [comment]
I'm interested in this as well.

If there's another way of specifying features with cargo bundle, I'd be happy to know that :)

**Comment by ArturKovacs** [comment]
I'd like to implement this. But as I'm seeing little activity recently, I'm wondering if I open a PR will it be considered for merging?

**Comment by mdsteele** [comment]
Hi, sorry for the lack of activity lately.  If you send a PR, I will try to review it.
