### ISSUE TITLE
Error: the source path is not an existing regular file

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [burtonageo/cargo-bundle#39]
Have a project with this structure:

<img width="207" alt="screen shot 2018-02-04 at 14 31 05" src="https://user-images.githubusercontent.com/5529132/35778008-148f07a4-09b8-11e8-82d2-93940e529d8e.png">

and this Cargo.toml:

```
[[bin]]
name = "flowc"
path = "src/flowc.rs"

[package.metadata.bundle]
identifier = "net.mackenzie-serres.flow.flowc"
icon = ["icons/32x32.png", "icons/128x128.png"]
resources = ["resources"]
```
(parts removed for brevity)

when I run "cargo bundle" I get this error:
```
cargo bundle
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
    Bundling flowc.app
Error: the source path is not an existing regular file
```

Any ideas of what is wrong?

**Comment by mdsteele** [comment]
Hmm, odd.  That does seem like it should work, it it's not clear to me what's causing the error.  (Clearly, cargo-bundle's error reporting could use some work; I'll look into that.)

Does your project happen to be available somewhere publicly where I could try bundling it to try to diagnose?

**Comment by mdsteele** [comment]
Alternatively, I believe that if you run cargo-bundle with the environment variable RUST_BACKTRACE=1 set, you should get a backtrace with the error; if you could post that backtrace here, that would be great.

**Comment by andrewdavidmackenzie** [comment]
Here's the backtrace (not so useful I think):

> Error: the source path is not an existing regular file
> stack backtrace:
>    0:        0x10c059e6e - backtrace::backtrace::trace::hc8f67935cd0b5b66
>    1:        0x10c059eac - backtrace::capture::Backtrace::new::h18c3b3b79d22977f
>    2:        0x10c0594b6 - error_chain::make_backtrace::hdcc4f1aacd973613
>    3:        0x10c059598 - _$LT$error_chain..State$u20$as$u20$core..default..Default$GT$::default::hda5dc645b6627964
>    4:        0x10bfce18b - cargo_bundle::bundle::osx_bundle::bundle_project::h0122419e7e2c7dac
>    5:        0x10bfd9454 - cargo_bundle::main::he1838a35c736bdb0
>    6:        0x10c1501bc - __rust_maybe_catch_panic
>    7:        0x10c143c68 - std::rt::lang_start::h7919b8561d5d8bb1

I'll try to reproduce with a simpler case than my project, and if I can't then I'll get back to you to reproduce it using mine.

**Comment by andrewdavidmackenzie** [comment]
In fact, I decided to just push by (broken) project, so you can clone and attempt to bundle it:

https://github.com/andrewdavidmackenzie/flow/

I just realized that the folder/sub-project I am trying to bundle is part of a cargo workspace (see Cargo.toml file in root directory) and maybe that is the source of the problem, as the binary (flowc) is compiled into the target folder under the root (flow) folder - and probably not found by cargo-bundler... I noticed in the code that the binary path is built from the folder plus the name of the package in Cargo.toml If that is confirmed, then maybe I can help you make it "workspace aware"...

To reproduce:
- cd flowc
- cargo bundle

After downloading and compiling everything, that should give you this output:

> Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
>     Bundling flowc.app
> Error: the source path is not an existing regular file

leave you with this content:

> tree target/
> target/
> `-- debug
>     `-- flowc.app
>         `-- Contents
>             |-- Info.plist
>             |-- MacOS             <--- No binary in here
>             `-- Resources
>                 |-- flowc.icns
>                 `-- lib
>                     `-- test.toml

**Comment by mdsteele** [comment]
Ah, okay, that's the problem then; `cargo-bundle` currently has no understanding of workspaces.

The place to address that would be in `src/bundle/settings.rs`.  When we parse the project's `Cargo.toml`, we need to also check for workspaces to determine the correct value for `target_dir`.

**Comment by andrewdavidmackenzie** [comment]
I've never worked on a cargo command before, but I could take a look at
that if you want...

Some pointers on how to work on it (e.g. tell cargo where to find binary
etc...) would be helpful, otherwise I can look for that info on the web...

**Comment by andrewdavidmackenzie** [comment]
BTW: Just to confirm, that via a quick code-hack to make cargo-bundle use the path of the parent Cargo.toml in the workspace I was able to make it package the app OK. Hence, working on https://github.com/burtonageo/cargo-bundle/issues/42
