### ISSUE TITLE
Track valid Cargo.toml format

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [burtonageo/cargo-bundle#46]
While implementing workspace awareness, I have realized that the definition of CargoSettings does not contemplate all fields of a Cargo.toml file.

e.g. a Cargo.toml file with a "workspace" table broke the deserialization as an unexpected field.
e.g. when parsing 'parent' Cargo.toml files in a workspace setup) the lack of a package table broke it.

I suggest we add some tests to test Cargo.toml deserialization against valid Cargo formats with newer fields and lacking some optional ones.

Ideally (I haven't checked) the Cargo project would offer a crate that defines the struct and deserialization using serde, then we could all use it directly and track updates.

**Comment by mdsteele** [comment]
Tests for this seem like a good idea; I'll see about adding some.  (Right now, `cargo-bundle` has no tests for anything, and I keep meaning to fix that.)

**Comment by andrewdavidmackenzie** [comment]
Once I merge the other stuff, I can help add some here- system tests with various Cargo.toml examples, not unit tests...

**Comment by mdsteele** [comment]
Added a basic unit test in #50, which I think is helpful as a sanity check.  But yes, it would be great to have more thorough system tests as well, if you're up for taking that on.

**Comment by andrewdavidmackenzie** [comment]
As the project is just a bin and has no libraries, tests in the "/tests" folder are not so useful (you could probably delete that folder and the empty test in it).
https://doc.rust-lang.org/1.20.0/book/second-edition/ch11-03-test-organization.html#integration-tests

I couldn't do exactly what I planned (invoking CargoSettings::load() from tests there...) but I can basically do the same from tests within settings.rs file. Will send a PR soon.

**Comment by andrewdavidmackenzie** [comment]
Here is a WIP commit for you to look at:
https://github.com/burtonageo/cargo-bundle/commit/579bd5323262b11cda4fbc94c0ece6679ef98129

I've got a bit of git confusion/mess to clean up before preparing a PR, but thought I'd share that with you to see if you think it's going in the right direction, before cleaning things up and sending the PR.
