### ISSUE TITLE
Issue installing a deb

### ISSUE THREAD

**Issue by alexjgriffith** [burtonageo/cargo-bundle#59]
When testing cargo-bundle to bundle and install the example project I run into the following error

```
Error while installing package: parsing file '/var/lib/dpkg/tmp.ci/control' near line 1
```

I'm using[ Eddy](https://github.com/donadigo/eddy) to manage my deb installs, it might be an issue on their end.

**Comment by mdsteele** [comment]
Whoops, I think the problem is that the bundle name of the example ("Hello World") has a space in it, and we're using that as the package name in the deb control file, but spaces aren't allowed there.  Probably we should replace spaces with hyphens for that field.
