### ISSUE TITLE
gtk-rs program does not receive all keyboard input

### ISSUE THREAD

**Issue by languitar** [burtonageo/cargo-bundle#7]
I am not sure what is actually the cause here, but I tried to bundle a simple gtk-rs program and after launching, normal keys do not work in a text box. Delete, arrow keys etc., however, work perfectly. This doesn't happen when the program is run from the command line.

**Comment by mdsteele** [comment]
That seems odd.  Do you have a link to the code for the program you're seeing this problem with?  Also, what OS/version is this on?

**Comment by languitar** [comment]
This happens with https://github.com/languitar/passgui. Manually starting the program with `cargo run` works. Inside the bundle it doesn't receive input.

Please note that due to a GTK bug, the window doesn't launch in the foreground. :/

**Comment by languitar** [comment]
Any updates on this one? This unfortunately blocks my use of this.

**Comment by andrewdavidmackenzie** [comment]
The cases you compare are both debug builds, and there's not a release build with optimizations involved?

**Comment by languitar** [comment]
Can't reproduce the issue anymore. Strange. All were debug builds.
