### ISSUE TITLE
Cargo.lock is too old to build cargo-bundle

### ISSUE THREAD

**Issue by dagit** [burtonageo/cargo-bundle#8]
I tried to build cargo-bundle and it failed (sorry I don't have the message handy), but someone pointed out to me that if you run `cargo update` and then `cargo install` things work out.

Please run `cargo update` and check in the new `Cargo.lock` and make a new release.

Thanks!

**Comment by coder543** [comment]
Also, it would be great if @burtonageo could update the crate on crates.io. It is 10 months old at this point.

**Comment by mdsteele** [comment]
628ee08 and 514545f seem to have fixed Cargo.lock and it is now building again with Rust 1.15.1.

**Comment by mdsteele** [comment]
The crate has now been updated (to v0.1.0) on crates.io.
