### ISSUE TITLE
cargo-bundle on crates.io is 2 years out of date.

### ISSUE THREAD

**Issue by simlay** [burtonageo/cargo-bundle#85]
I updated cargo-bundle via `cargo install --force cargo-bundle` and found myself with an older version.

I've since updated via `cargo install cargo-bundle --git https://github.com/burtonageo/cargo-bundle` to get the version I actually wanted but figured I'd write a ticket for the next person who ends up going down a small rabbit hole and wonders why it's broken.

**Comment by ArturKovacs** [comment]
I am also interested in when the latest changes will be published. Being able to customize the `Exec` field of the .desktop file is essential for https://github.com/ArturKovacs/emulsion/issues/86

**Comment by mdsteele** [comment]
Hi, sorry for the slow reply.  I've bumped the version number to 0.5.0 and pushed a [new version](https://crates.io/crates/cargo-bundle/0.5.0) to crates.io.
